name: Lewis Personal Website
run-name: ${{ github.actor }} is using GitHub Actions

env:
  AZURE_WEBAPP_NAME: Personal-Website-Lewis
  PYTHON_VERSION: '3.9'

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup/setup-python@v4
        with:
            python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Building container
        run: |
          make build
      - name: Run container
        run: |
          make run