name: Lewis Personal Website
run-name: ${{ github.actor }} is using GitHub Actions

env:
  AZURE_WEBAPP_NAME: Personal-Website-Lewis
  PYTHON_VERSION: '3.9'
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Building container and installing dependencies
        run: |
          make build
      - name: Run application
        run: |
          make run